//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autoscreen.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Interval {
            get {
                return ((int)(this["Interval"]));
            }
            set {
                this["Interval"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.0.5")]
        public string ApplicationVersion {
            get {
                return ((string)(this["ApplicationVersion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageFormatFilter {
            get {
                return ((string)(this["ImageFormatFilter"]));
            }
            set {
                this["ImageFormatFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScreenshotsDirectory {
            get {
                return ((string)(this["ScreenshotsDirectory"]));
            }
            set {
                this["ScreenshotsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int SlideshowDelay {
            get {
                return ((int)(this["SlideshowDelay"]));
            }
            set {
                this["SlideshowDelay"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto Screen Capture")]
        public string ApplicationName {
            get {
                return ((string)(this["ApplicationName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int CaptureLimit {
            get {
                return ((int)(this["CaptureLimit"]));
            }
            set {
                this["CaptureLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaptureLimitCheck {
            get {
                return ((bool)(this["CaptureLimitCheck"]));
            }
            set {
                this["CaptureLimitCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TakeInitialScreenshotCheck {
            get {
                return ((bool)(this["TakeInitialScreenshotCheck"]));
            }
            set {
                this["TakeInitialScreenshotCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ImageResolutionRatio {
            get {
                return ((int)(this["ImageResolutionRatio"]));
            }
            set {
                this["ImageResolutionRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SlideSkipCheck {
            get {
                return ((bool)(this["SlideSkipCheck"]));
            }
            set {
                this["SlideSkipCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SlideSkip {
            get {
                return ((int)(this["SlideSkip"]));
            }
            set {
                this["SlideSkip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenOnScreenCaptureStopCheck {
            get {
                return ((bool)(this["OpenOnScreenCaptureStopCheck"]));
            }
            set {
                this["OpenOnScreenCaptureStopCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExitOnCloseWindowCheck {
            get {
                return ((bool)(this["ExitOnCloseWindowCheck"]));
            }
            set {
                this["ExitOnCloseWindowCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenOnApplicationStartupCheck {
            get {
                return ((bool)(this["OpenOnApplicationStartupCheck"]));
            }
            set {
                this["OpenOnApplicationStartupCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ImageFormatIndex {
            get {
                return ((int)(this["ImageFormatIndex"]));
            }
            set {
                this["ImageFormatIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CaptureStartAtCheck {
            get {
                return ((bool)(this["CaptureStartAtCheck"]));
            }
            set {
                this["CaptureStartAtCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CaptureStopAtCheck {
            get {
                return ((bool)(this["CaptureStopAtCheck"]));
            }
            set {
                this["CaptureStopAtCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11/20/2013 08:00:00")]
        public global::System.DateTime CaptureStartAtValue {
            get {
                return ((global::System.DateTime)(this["CaptureStartAtValue"]));
            }
            set {
                this["CaptureStartAtValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11/20/2013 17:00:00")]
        public global::System.DateTime CaptureStopAtValue {
            get {
                return ((global::System.DateTime)(this["CaptureStopAtValue"]));
            }
            set {
                this["CaptureStopAtValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CaptureOnSaturdayCheck {
            get {
                return ((bool)(this["CaptureOnSaturdayCheck"]));
            }
            set {
                this["CaptureOnSaturdayCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CaptureOnSundayCheck {
            get {
                return ((bool)(this["CaptureOnSundayCheck"]));
            }
            set {
                this["CaptureOnSundayCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaptureOnMondayCheck {
            get {
                return ((bool)(this["CaptureOnMondayCheck"]));
            }
            set {
                this["CaptureOnMondayCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaptureOnTuesdayCheck {
            get {
                return ((bool)(this["CaptureOnTuesdayCheck"]));
            }
            set {
                this["CaptureOnTuesdayCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaptureOnWednesdayCheck {
            get {
                return ((bool)(this["CaptureOnWednesdayCheck"]));
            }
            set {
                this["CaptureOnWednesdayCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaptureOnThursdayCheck {
            get {
                return ((bool)(this["CaptureOnThursdayCheck"]));
            }
            set {
                this["CaptureOnThursdayCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaptureOnFridayCheck {
            get {
                return ((bool)(this["CaptureOnFridayCheck"]));
            }
            set {
                this["CaptureOnFridayCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CaptureOnTheseDaysCheck {
            get {
                return ((bool)(this["CaptureOnTheseDaysCheck"]));
            }
            set {
                this["CaptureOnTheseDaysCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PNG")]
        public string ScheduleImageFormat {
            get {
                return ((string)(this["ScheduleImageFormat"]));
            }
            set {
                this["ScheduleImageFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeyloggingEnabledCheck {
            get {
                return ((bool)(this["KeyloggingEnabledCheck"]));
            }
            set {
                this["KeyloggingEnabledCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("keylog.txt")]
        public string KeyloggingFile {
            get {
                return ((string)(this["KeyloggingFile"]));
            }
            set {
                this["KeyloggingFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScheduleOnAtStartupCheck {
            get {
                return ((bool)(this["ScheduleOnAtStartupCheck"]));
            }
            set {
                this["ScheduleOnAtStartupCheck"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gavin Kendall")]
        public string ApplicationAuthor {
            get {
                return ((string)(this["ApplicationAuthor"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DemoModeCheck {
            get {
                return ((bool)(this["DemoModeCheck"]));
            }
            set {
                this["DemoModeCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSlideshowAfterScreenCaptureStopCheck {
            get {
                return ((bool)(this["ShowSlideshowAfterScreenCaptureStopCheck"]));
            }
            set {
                this["ShowSlideshowAfterScreenCaptureStopCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaptureStartOnScheduleCheck {
            get {
                return ((bool)(this["CaptureStartOnScheduleCheck"]));
            }
            set {
                this["CaptureStartOnScheduleCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SearchScreenshotsOnStopScreenCaptureCheck {
            get {
                return ((bool)(this["SearchScreenshotsOnStopScreenCaptureCheck"]));
            }
            set {
                this["SearchScreenshotsOnStopScreenCaptureCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseWindowOnStartCaptureCheck {
            get {
                return ((bool)(this["CloseWindowOnStartCaptureCheck"]));
            }
            set {
                this["CloseWindowOnStartCaptureCheck"] = value;
            }
        }
    }
}
